# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flux < Formula
  desc "Kconf helps you with kubeconfig manipulation"
  homepage "https://github.com/sn3d/"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sn3d/kconf/releases/download/v0.2.3/kconf_macOS_arm64.tar.gz"
      sha256 "71fd9d9695434f50802703ac37bb2c3a6c4bd830a50a66fdd87ba87148f21603"

      def install
        bin.install "kconf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sn3d/kconf/releases/download/v0.2.3/kconf_macOS_amd64.tar.gz"
      sha256 "ef819b12a86dc2adcdcc73a2de1e62b6eca959751fdb30049c6505cf90f0ef23"

      def install
        bin.install "kconf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sn3d/kconf/releases/download/v0.2.3/kconf_linux_arm.tar.gz"
      sha256 "aa3d72b3a45d8b0fca3bef6e00034df368e2b5128c9cc72bf4cea8938e37ad65"

      def install
        bin.install "kconf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sn3d/kconf/releases/download/v0.2.3/kconf_linux_arm64.tar.gz"
      sha256 "e75e4daf42d905341e0e45b47602d5d829323894949fe77a91092d9f045df7f2"

      def install
        bin.install "kconf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sn3d/kconf/releases/download/v0.2.3/kconf_linux_amd64.tar.gz"
      sha256 "6af10e0f9e96e9bddfad0f3af7878073f9587ce9ee11cc1e76f2731f9b868065"

      def install
        bin.install "kconf"
      end
    end
  end
end
