# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kconf < Formula
  desc "Kconf helps you with kubeconfig manipulation"
  homepage "https://github.com/sn3d/"
  version "0.4.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sn3d/kconf/releases/download/v0.4.3/kconf_macOS_amd64.tar.gz"
      sha256 "bc25cd16eae9f4c6081f8b2a9176743093d05f696a8780e530c7d355032464e4"

      def install
        bin.install "kconf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sn3d/kconf/releases/download/v0.4.3/kconf_macOS_arm64.tar.gz"
      sha256 "835293ca623afb862ab6a570679b34677172e6c69b3f411eb96ae3523dfc8755"

      def install
        bin.install "kconf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sn3d/kconf/releases/download/v0.4.3/kconf_linux_arm64.tar.gz"
      sha256 "c3a89b2cca07be23f44c84abfa7ed1e4491242e5bf1ced99b1d2cbe28cfd0c1f"

      def install
        bin.install "kconf"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sn3d/kconf/releases/download/v0.4.3/kconf_linux_arm.tar.gz"
      sha256 "2d8c676e44bc52ba19bc01909d5622246755467dd2a796d25110f76555c3bf54"

      def install
        bin.install "kconf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sn3d/kconf/releases/download/v0.4.3/kconf_linux_amd64.tar.gz"
      sha256 "1d489d5527e6efab7270da8529d4912f38fea1388e9fd1dea8600efe934172d1"

      def install
        bin.install "kconf"
      end
    end
  end
end
