# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kconf < Formula
  desc "Kconf helps you with kubeconfig manipulation"
  homepage "https://github.com/sn3d/"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sn3d/kconf/releases/download/v0.4.1/kconf_macOS_amd64.tar.gz"
      sha256 "78df8698899faf36bad624dec3750353671dcd03dcc80cbd5cc00cb32c7e9da6"

      def install
        bin.install "kconf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sn3d/kconf/releases/download/v0.4.1/kconf_macOS_arm64.tar.gz"
      sha256 "e46dfd531e58cc4b4deb56fbf92781585afa6bb82ab3633433cd9808fbd40f1d"

      def install
        bin.install "kconf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sn3d/kconf/releases/download/v0.4.1/kconf_linux_arm64.tar.gz"
      sha256 "1154a451b809708940a1e69e60ba8520adb8cbd0bfff058401cb02d6f72e691b"

      def install
        bin.install "kconf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sn3d/kconf/releases/download/v0.4.1/kconf_linux_amd64.tar.gz"
      sha256 "797c37fdb60c8e4f28a8665dd24188d1cd5652ba638b5d8cea153541e794d06e"

      def install
        bin.install "kconf"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sn3d/kconf/releases/download/v0.4.1/kconf_linux_arm.tar.gz"
      sha256 "e2c11b9ea2670f5777a132f031ab3f5d2b70506b72ed6267c5d34a760060a940"

      def install
        bin.install "kconf"
      end
    end
  end
end
