# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Silkyswift < Formula
  desc "Minimal CONNECT-tunnel HTTPS intercepting proxy that records api.anthropic.com traffic"
  homepage "https://github.com/sn3d/silkyswift"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sn3d/silkyswift/releases/download/v0.0.2/silkyswift_macOS_amd64.tar.gz"
      sha256 "07053ce0da739f138496c6920f16eb2de78c9d20ffb99042099285b4086ed1c6"

      define_method(:install) do
        bin.install "silkyswift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sn3d/silkyswift/releases/download/v0.0.2/silkyswift_macOS_arm64.tar.gz"
      sha256 "09fd200ac38a13571997a22d9e4dc6c57c66dd2478934db559bb98850c1215f0"

      define_method(:install) do
        bin.install "silkyswift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sn3d/silkyswift/releases/download/v0.0.2/silkyswift_linux_amd64.tar.gz"
      sha256 "8a968b179d9545e82789bac3fbd4d4156b7c371679fab935f796071d4068e722"
      define_method(:install) do
        bin.install "silkyswift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sn3d/silkyswift/releases/download/v0.0.2/silkyswift_linux_arm64.tar.gz"
      sha256 "9e998d3a58ff254d96ae22446f51b6868bb647fb8be43c807b8ae4c5562c75e5"
      define_method(:install) do
        bin.install "silkyswift"
      end
    end
  end

  test do
    system "#{bin}/silkyswift", "--version"
  end
end
