# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tm < Formula
  desc "Local task manager for agents"
  homepage "https://github.com/sn3d/tm"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sn3d/tm/releases/download/v0.2.1/tm_macOS_amd64.tar.gz"
      sha256 "433d871f23e5ed03cfac82b2fd0ba656a768588a0e4e986002424da533765eea"

      define_method(:install) do
        bin.install "tm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sn3d/tm/releases/download/v0.2.1/tm_macOS_arm64.tar.gz"
      sha256 "5c319c7915940d908b96c24e5f125a082541d2dcd15155c66e5dc49387d94670"

      define_method(:install) do
        bin.install "tm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sn3d/tm/releases/download/v0.2.1/tm_linux_amd64.tar.gz"
      sha256 "1f9df9e893e5ae8801c7921e9b19753b5f6532b43d8271e0681aa3370dcb86de"
      define_method(:install) do
        bin.install "tm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sn3d/tm/releases/download/v0.2.1/tm_linux_arm64.tar.gz"
      sha256 "aa6660a00386d5c37bb02398e9935944e6a8266463f8383c32b044c0d52ab56b"
      define_method(:install) do
        bin.install "tm"
      end
    end
  end

  test do
    system "#{bin}/tm", "--version"
  end
end
