# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tm < Formula
  desc "Local task manager for agents"
  homepage "https://github.com/sn3d/tm"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sn3d/tm/releases/download/v0.2.0/tm_macOS_amd64.tar.gz"
      sha256 "d08e49bbb4d556d5a4985de155ac20e0e40451b05387f018c3cb955599fb1235"

      define_method(:install) do
        bin.install "tm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sn3d/tm/releases/download/v0.2.0/tm_macOS_arm64.tar.gz"
      sha256 "8c7de443d4ba7f5358fa357890dc1c6a0ddb91bfce2e7290e78ed876cba4fc6d"

      define_method(:install) do
        bin.install "tm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sn3d/tm/releases/download/v0.2.0/tm_linux_amd64.tar.gz"
      sha256 "76cbd434fb8911708e3b24814988c78024abceeb243fd31042dc14cf4f5be864"
      define_method(:install) do
        bin.install "tm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sn3d/tm/releases/download/v0.2.0/tm_linux_arm64.tar.gz"
      sha256 "627f3a679d965231a6da41c0e4153dbbb8cb662d1613c610ddc870df77f0021b"
      define_method(:install) do
        bin.install "tm"
      end
    end
  end

  test do
    system "#{bin}/tm", "--version"
  end
end
