# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tm < Formula
  desc "Local task manager for agents"
  homepage "https://github.com/sn3d/tm"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sn3d/tm/releases/download/v0.1.0/tm_macOS_amd64.tar.gz"
      sha256 "8e75cdbf5c2ddf5c48feb127139c30cfc739d8c944dcc7ed9f95865159ee0186"

      define_method(:install) do
        bin.install "tm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sn3d/tm/releases/download/v0.1.0/tm_macOS_arm64.tar.gz"
      sha256 "fcbca41b11b9381128bf6a4077d98062794de71f2d82d4fd7721573d9a81c3cf"

      define_method(:install) do
        bin.install "tm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sn3d/tm/releases/download/v0.1.0/tm_linux_amd64.tar.gz"
      sha256 "c3652678a15f133d898cbfa5ded1c7f5b9f8daf2f68e9b3122d8e40ad73cebbc"
      define_method(:install) do
        bin.install "tm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sn3d/tm/releases/download/v0.1.0/tm_linux_arm64.tar.gz"
      sha256 "84c38fa7464cee5a8c98927a5be446c3da2ca8968ce6b5273ae8c7e4f8fe8f25"
      define_method(:install) do
        bin.install "tm"
      end
    end
  end

  test do
    system "#{bin}/tm", "--version"
  end
end
